
// COURSE ---------------------------------------------------------------------------
export const GET_COURSE_BEGIN="GET_COURSE_BEGIN";
export const GET_COURSE_SUCCESS="GET_COURSE_SUCCESS";
export const GET_COURSE_FAIL="GET_COURSE_FAIL";

export const GET_CATEGORY_COURSE_BEGIN="GET_CATEGORY_COURSE_BEGIN";
export const GET_CATEGORY_COURSE_SUCCESS="GET_CATEGORY_COURSE_SUCCESS";
export const GET_CATEGORY_COURSE_FAIL="GET_CATEGORY_COURSE_FAIL";


export const SEARCH_COURSE="SEARCH_COURSE";

export const FILTER_COURSE="FILTER_COURSE";
export const FILTER_COURSE_SUCCESS="FILTER_COURSE_SUCCESS";
export const FILTER_COURSE_FAIL="FILTER_COURSE_FAIL";


export const DETAIL_COURSE_BEGIN="DETAIL_COURSE_BEGIN";
export const DETAIL_COURSE_SUCCESS="DETAIL_COURSE_SUCCESS";
export const DETAIL_COURSE_FAIL="DETAIL_COURSE_FAIL";

export const ADD_CARD_SUCCESS ="ADD_CARD_SUCCESS";
export const ADD_CARD_FAIL ="ADD_CARD_FAIL";

export const DELETE_CARD_SUCCESS="DELETE_CARD_SUCCESS";
export const DELETE_CARD_FAIL="DELETE_CARD_FAIL";

export const GHIDANH_SUCCESS ="GHIDANH_SUCCESS";
export const GHIDANH_FAIL="GHIDANH_FAIL";


export const GET_COURSE_PAGINATE_BEGIN="GET_COURSE_PAGINATE_BEGIN";
export const GET_COURSE_PAGINATE_SUCCESS="GET_COURSE_PAGINATE_SUCCESS";
export const GET_COURSE_PAGINATE_ERROR="GET_COURSE_PAGINATE_ERROR";


export const CHECK_AUTHOR_BEGIN="CHECK_AUTHOR_BEGIN"
export const CHECK_AUTHOR_SUCCESS="CHECK_AUTHOR_SUCCESS"
export const CHECK_AUTHOR_FAIL="CHECK_AUTHOR_FAIL"


export const CHECK_TYPE_COURSE_BEGIN ="CHECK_TYPE_COURSE_BEGIN";
export const CHECK_TYPE_COURSE_SUCCESS ="CHECK_TYPE_COURSE_SUCCESS";
export const CHECK_TYPE_COURSE_FAIL ="CHECK_TYPE_COURSE_FAIL";




//USER ----------------------------------------------------

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT="USER_LOGOUT";

export const INFO_USER_BEGIN="INFO_USER_BEGIN";
export const INFO_USER_SUCCESS="INFO_USER_SUCCESS";
export const INFO_USER_FAIL="INFO_USER_FAIL";

export const UPDATE_USER_BEGIN="UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL="UPDATE_USER_FAIL";


export const USER_GHIDANH_BEGIN="USER_GHIDANH_BEGIN";
export const USER_GHIDANH_SUCCESS="USER_GHIDANH_SUCCESS";
export const USER_GHIDANH_FAIL="USER_GHIDANH_FAIL";

export const INFO_TAIKHOAN="INFO_TAIKHOAN";

//ADMIN-------------------------------------------------------------------------------------
export const ADMIN_LOGIN__BEGIN="ADMIN_LOGIN__BEGIN";
export const ADMIN_LOGIN__SUCCESS="ADMIN_LOGIN__SUCCESS";
export const ADMIN_LOGIN__FAIL="ADMIN_LOGIN__FAIL";


export const GET_USER_BEGIN ="GET_USER_BEGIN";
export const GET_USER_SUCCESS ="GET_USER_SUCCESS";
export const GET_USER_FAIL ="GET_USER_FAIL";


